### ISSUE TITLE
cannot import name 'LocalDeviceObject' in v0.17.0 or later

### ISSUE THREAD

**Issue by guangyuzhang** [JoelBender/bacpypes#197]
There is an error in v0.17.0 and 0.17.1, 
from bacpypes.service.device import LocalDeviceObject
ImportError: cannot import name 'LocalDeviceObject'

It works fine in v0.16.7

**Comment by JoelBender** [comment]
This was moved to a new submodule called 'local' in [0.17.0](https://github.com/JoelBender/bacpypes/wiki/Release-Notes#localdeviceobject-moved) and it will be joined with other implementation classes, you'll notice that the file and schedule objects have been moved there as well.

**Comment by jakebrinkmann** [comment]
`from bacpypes.local.device import LocalDeviceObject`

This should perhaps be updated: https://github.com/JoelBender/bacpypes/blob/a3c9f1eb4685272dad2ac4d08fedc39e871cac7a/doc/source/samples/sample001.rst
